name: Deploy Front End

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4

      - name: Sync Files
        run: |
          rsync -av --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'node_modules' \
            --exclude 'build' \
            --exclude 'dist' \
            --exclude '.env' \
            ./ /opt/apps/apinexus/frontend/app/

      - name: Deploy Admin Application
        run: |
          set -e

          cd /opt/apps/apinexus/frontend/app

          docker compose up -d --build --force-recreate

          docker image prune -f

          echo "Admin deployment completed successfully."
